# Generated by Django 4.0 on 2022-02-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CursoId', models.IntegerField(default=0)),
                ('EstudianteID', models.IntegerField(default=0)),
                ('Fecha', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='categorias',
            name='Descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Descripcion',
            field=models.TextField(),
        ),
    ]
